package com.mygdx.catan.enums;

public enum ProgressCardType {

    ALCHEMIST,
    CRANE,
    ENGINEER,
    INVENTOR,
    IRRIGATION,
    MEDICINE,
    MINING,
    PRINTER,
    ROADBUILDING,
    SMITH,
    BISHOP,
    CONSTITUTION,
    DESERTER,
    DIPLOMAT,
    INTRIGUE,
    SABOTEUR,
    SPY,
    WARLORD,
    WEDDING,
    COMMERCIALHARBOUR,
    MASTERMERCHANT,
    MERCHANTFLEET,
    MERCHANT,
    RESOURCEMONOPOLY,
    TRADEMONOPOLY
}
